spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 21002
  tomcat:
    uri-encoding: UTF-8
    max-http-form-post-size: 2MB
  servlet:
    session:
      timeout: 2h
      cookie:
        http-only: true
        same-site: lax

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator
  endpoint:
    health:
      show-details: never
  server:
    port: 21003

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

app:
  page:
    review-size: 15
    room-size: 10
    community-size: 15
  oci:
    config-file: ~/.oci/config
    profile: DEFAULT
    namespace: axw45xvpnfol
    bucket: MyBucket
    region: ap-chuncheon-1
